<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Profile;
use AppBundle\Entity\Comment;
use Doctrine\ORM\Query;

use Pagerfanta\Adapter\DoctrineORMAdapter;
use Pagerfanta\Pagerfanta;
/**
 * ProfileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends \Doctrine\ORM\EntityRepository
{

	public function getComments(Profile $profile, int $page = 1)
    {
        $queryBuilder = $this->createQueryBuilder('c');

        $queryBuilder->andWhere(':profile = c.profile')->setParameter('profile', $profile);

        $query = $queryBuilder
            ->andWhere('c.isPublished = 1')
            ->orderBy('c.createdAt', 'DESC')
            ->getQuery();

         return $this->createPaginator($query, $page);
    }


    private function createPaginator(Query $query, int $page): Pagerfanta
    {
        $paginator = new Pagerfanta(new DoctrineORMAdapter($query));
        $paginator->setMaxPerPage(Comment::NUM_ITEMS);
        $paginator->setCurrentPage($page);

        return $paginator;
    }

}
