<?php

namespace AppBundle\Repository;

/**
 * PageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PageRepository extends \Doctrine\ORM\EntityRepository
{
	public function findMenuPages() {
		$queryBuilder = $this->createQueryBuilder('p');
		$queryBuilder->andWhere('p.inMenu = TRUE');

		return $queryBuilder
            ->orderBy('p.createdAt', 'ASC')
            ->getQuery()
            ->getResult();

	}
}
