<?php

namespace AppBundle\Repository;

/**
 * ProvinceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProvinceRepository extends \Doctrine\ORM\EntityRepository
{

	/**
     * @return Province[]
     */
    public function findBySearchQuery(string $query): array
    {
        $queryBuilder = $this->createQueryBuilder('p');

        if ( is_numeric($query) ) {
               $queryBuilder
                ->orWhere('p.zip LIKE :q')
                ->setParameter('q', '%' . $query . '%')
            ;
        } else {
            $queryBuilder
                ->orWhere('p.name LIKE :q')
                ->setParameter('q', '%' . $query . '%')
            ;
        }

        return $queryBuilder
            ->orderBy('p.name', 'DESC')
            ->getQuery()
            ->getResult();
    }
}
