easy_admin:
    site_name: Administration

    entities:
        Profile:
            class: AppBundle\Entity\Profile
            controller: AppBundle\Controller\Admin\ProfileAdminController
            label: Profiles
            list:
                fields:
                    - id
                    - name
                    - { property: 'photo', type: 'image', base_path: '%app.path.profile_photos%' }
                    - isPublished
                    - specialty
                    - district
                    - province
                    - updatedAt
            form:
                fields:
                    - { type: group, css_class: "col-sm-6", label: 'Détails'}
                    - name
                    - slug
                    - isPublished
                    - { property: 'photoFile', type: 'vich_image' }
                    - { property: 'specialty', type: 'easyadmin_autocomplete' }
                    - { property: 'tags', type: 'easyadmin_autocomplete' }
                    - description
                    - { type: group, css_class: "col-sm-6", label: 'Contact'}
                    - phone
                    - mobile
                    - email
                    - { type: group, css_class: "col-sm-6", label: 'Adresse'}
                    - { property: 'province', css_class: 'js-province' }
                    - { property: 'district', type: 'easyadmin_autocomplete', css_class: 'js-district' }
                    - address
                    - { property: 'latitude', type: text, css_class: 'js-latitude' }
                    - { property: 'longitude', type: text, css_class: 'js-longitude' }
                    -
                        property: map
                        type: text
                        css_class: 'js-pick-location'
                        type_options:
                            mapped: false
            new:
                fields:
                    - '-slug'
            show:
                fields:
                    - { property: 'photo', type: 'photo', base_path: '%app.path.profile_photos%' }

        Specialty:
            class: AppBundle\Entity\Specialty
            label: Spécialités
            form:
                fields:
                    - name
                    - slug
            new:
                fields:
                    - '-slug'
        Tag:
            class: AppBundle\Entity\Tag
            label: Expertises
            form:
                fields:
                    - name
                    - slug
            new:
                fields:
                    - '-slug'
        Province:
            class: AppBundle\Entity\Province
            label: Wilayas
            form:
                fields:
                    - name
                    - slug
                    - zip
            new:
                fields:
                    - '-slug'
        District:
            class: AppBundle\Entity\District
            label: Communes
            form:
                fields:
                    - name
                    - slug
                    - province
                    - zip
            new:
                fields:
                    - '-slug'
            new:
                fields:
                    - '-slug'
        User:
            class: AppBundle\Entity\User
            controller: AppBundle\Controller\Admin\UserAdminController
            label: Utilisateurs
            form:
                fields:
                    - username
                    - email
                    - enabled
                    - lastLogin
                    - { property: 'plainPassword', type: 'text', type_options: { required: false } }
                    - { property: 'roles', type: 'choice', type_options: { multiple: true, choices: { 'ROLE_USER': 'ROLE_USER', 'ROLE_ADMIN': 'ROLE_ADMIN' } } }
        Comment:
            class: AppBundle\Entity\Comment
            label: Commentaires