AppBundle\Entity\Comment:
    type:  entity
    table: comments
    ChangeTrackingPolicy: DEFERRED_EXPLICIT
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    manyToOne:
        thread:
            targetEntity: AppBundle\Entity\Profile
            nullable: false