AppBundle\Entity\Comment:
    type:  entity
    ChangeTrackingPolicy: DEFERRED_EXPLICIT
    repositoryClass: AppBundle\Repository\CommentRepository
    table: comments
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        content:
            type: text
        createdAt:
            type: datetime
        isPublished:
            type: boolean
    manyToOne:
        author:
            targetEntity: AppBundle\Entity\User
        profile:
            targetEntity: AppBundle\Entity\Profile
            inversedBy: comments
