AppBundle\Entity\District:
    type: entity
    table: districts
    repositoryClass: AppBundle\Repository\DistrictRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
        slug:
            type: string
            length: 190
            gedmo:
                slug:
                    unique: false
                    fields:
                        - name
        zip:
            type: integer
            length: 5
    manyToOne:
        province:
            targetEntity: Province
            inversedBy: districts
            joinColumn:
                name: province_id
                referencedColumnName: id
                nullable: false
    oneToMany:
        profiles:
            targetEntity: Profile
            mappedBy: district
            cascade: ["persist", "remove"]
    lifecycleCallbacks: {  }
