AppBundle\Entity\Profile:
    type: entity
    table: profiles
    ChangeTrackingPolicy: DEFERRED_EXPLICIT
    repositoryClass: AppBundle\Repository\ProfileRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
            nullable: true
        lastName:
            type: string
        firstName:
            type: string
            nullable: true
        isPublished:
            type: boolean
        photo:
            type: string
            nullable: true
        slug:
            type: string
            unique: true
            length: 190
            gedmo:
                slug:
                    unique: true
                    fields:
                        - title
                        - lastName
                        - firstName
        description:
            type: text
            nullable: true
        address:
            type: string
            nullable: true
        latitude:
            type: decimal
            precision: 12
            scale: 9
            nullable: true
        longitude:
            type: decimal
            precision: 12
            scale: 9
            nullable: true
        phone:
            type: string
            nullable: true
        mobile:
            type: string
            nullable: true
        email:
            type: string
            nullable: true
        createdAt:
            type: datetime
        updatedAt:
            type: datetime
            column: updated_at
    oneToMany:
        comments:
            targetEntity: AppBundle\Entity\Comment
            mappedBy: profile
            cascade: ["persist", "remove"]
    manyToOne:
#        user:
#            targetEntity: AppBundle\Entity\User
#            joinColumn:
#                name: user_id
#                referencedColumnName: id
#                nullable: false
        specialty:
            targetEntity: AppBundle\Entity\Specialty
            inversedBy: profiles
            joinColumn:
                name: specialty_id
                referencedColumnName: id
                nullable: false
        province:
            targetEntity: Province
            inversedBy: profiles
            joinColumn:
                name: province_id
                referencedColumnName: id
                nullable: false
        district:
            targetEntity: District
            inversedBy: profiles
            joinColumn:
                name: district_id
                referencedColumnName: id
                nullable: false
    manyToMany:
        tags:
            targetEntity: Tag
            cascade: ["persist"]
            inversedBy: profiles
            joinTable:
                name: profiles_tags
                joinColumns:
                    profile_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    tag_id:
                        referencedColumnName: id
    lifecycleCallbacks:
        preUpdate: [setUpdatedAt]
