AppBundle\Entity\Province:
    type: entity
    table: provinces
    repositoryClass: AppBundle\Repository\ProvinceRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
        slug:
            type: string
            unique: true
            length: 190
            gedmo:
                slug:
                    fields:
                        - name
        zip:
            type: integer
            length: 5
    oneToMany:
        profiles:
            targetEntity: Profile
            mappedBy: province
            cascade: ["persist", "remove"]
        districts:
            targetEntity: District
            mappedBy: province
            cascade: ["persist", "remove"]
    lifecycleCallbacks: {  }
